sudo: required

services:
  - docker

language: node_js

script:
  - echo 'hello with docker'
  - docker info
  - docker build -t szazo/travisdockertest
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push szazo/travisdockertest
